<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Password; 
use Illuminate\Support\Facades\Mail;     // For sending OTPs
use Illuminate\Support\Facades\Cache;    // For storing OTPs temporarily
use App\Mail\SuperAdminLoginCode;         // Our Mail class
use App\Support\InstitutionalIdGenerator;
use Illuminate\Support\Facades\Log;

class AuthController extends Controller
{
    /**
     * Handle an incoming browser registration request.
     */
    public function register(Request $request)
    {
        // 1. Validate incoming data payloads from the submission form.
        //    institutional_id is NOT accepted from the form anymore -- it is
        //    always generated by the server (see step 2) so two people can
        //    never submit/claim the same ID.
        // 🔒 SECURITY: the public registration form must NEVER be able to
        // create admin or super_admin accounts. Only 'student' and
        // 'teacher' are self-service roles. Admins are provisioned by a
        // super_admin (see SuperAdminController::adminStore), and there is
        // only ever supposed to be ONE super_admin per deployment — created
        // once, out-of-band (seeder/artisan command), never through a
        // public form. If this validation rule is ever loosened again,
        // anyone on the internet can grant themselves full system control.
        $data = $request->validate([
            'first_name' => 'required|string|max:255',
            'last_name'  => 'required|string|max:255',
            'email'      => 'required|string|email|max:255|unique:users,email',
            'password'   => 'required|string|min:8',
            'role'       => 'required|string|in:student,teacher',
        ]);

        // 🔒 MULTI-TENANCY: this platform hosts many universities in one
        // shared app. A self-registering student/teacher must land inside
        // THEIR OWN university's tenant, never floating unassigned and
        // never able to pick someone else's institution from a dropdown.
        // We match it automatically from their email domain against the
        // `institutions.domain` column (e.g. "student@rupp.edu.kh" ->
        // the institution whose domain is "rupp.edu.kh").
        //
        // If no institution owns that domain yet, we NO LONGER block
        // registration. Instead we auto-onboard the domain by creating a
        // new (active) institution row on the fly, so students/teachers
        // can always self-register on first use. A super_admin can rename
        // the auto-created institution, set a logo, etc. afterwards from
        // the admin panel.
        $emailDomain = strtolower(substr(strrchr($data['email'], '@'), 1));

        $institution = \App\Models\Institution::where('domain', $emailDomain)
            ->where('is_active', true)
            ->first();

        if (!$institution) {
            // Derive a human-friendly default name from the domain, e.g.
            // "rupp.edu.kh" -> "Rupp", "gmail.com" -> "Gmail". This is just
            // a starting point; a super_admin can rename it later.
            $label = ucfirst(strtok($emailDomain, '.'));

            $institution = \App\Models\Institution::firstOrCreate(
                ['domain' => $emailDomain],
                [
                    'name'      => $label,
                    'is_active' => true,
                ]
            );

            // Edge case: the domain existed already but was marked
            // inactive (e.g. a school the Super Admin deliberately
            // suspended). Respect that instead of silently reactivating it.
            if (!$institution->is_active) {
                return back()
                    ->withErrors(['email' => 'Your university\'s account on this platform is currently inactive. Please contact your Super Admin.'])
                    ->withInput($request->except('password'));
            }
        }

        $fullName = $data['first_name'] . ' ' . $data['last_name'];

        // 2. Server generates the unique institutional ID for the chosen
        //    role, scoped per institution so two different universities can
        //    both have a "STU-0001" without colliding.
        //    InstitutionalIdGenerator guarantees uniqueness even if many
        //    people register at the same instant.
        $institutionalId = InstitutionalIdGenerator::generate($data['role'], $institution->id);

        // 🔒 ROLE INTEGRITY: the "Registering as" dropdown is filled in by
        // the person themselves — nothing on the client can prove that a
        // "Teacher" signup is actually a real member of staff. Anyone can
        // pick Teacher off a public form. Because the teacher role carries
        // real privileges elsewhere in the app (creating/grading exams,
        // department assignment, teacher-only routes), we do NOT activate
        // self-registered teacher accounts immediately. They're created in
        // a 'pending' state and can't log in until an Admin at their
        // institution approves them from Admin > Users. Students carry no
        // elevated privileges from a self-declared role, so they stay
        // auto-active.
        $initialStatus = $data['role'] === 'teacher' ? 'pending' : 'active';

        // 3. Save and commit the user data fields into your database table
        $user = User::create([
            'full_name'        => $fullName,
            'email'            => $data['email'],
            'password_hash'    => Hash::make($data['password']), // Maps to your custom migration column
            'role'             => $data['role'],
            'status'           => $initialStatus,
            'institution_id'   => $institution->id,
            'institutional_id' => $institutionalId,
        ]);

        // Flash parameters to short-term session memory for your success page card layout
        return redirect()->route('register.success')->with([
            'registered_name'             => $user->full_name,
            'registered_email'            => $user->email,
            'registered_role'             => $user->role,
            'registered_institutional_id' => $user->institutional_id,
            'registered_pending_approval' => $initialStatus === 'pending',
        ]);
    }

    /**
     * Handle an incoming browser login form submission.
     */
    public function login(Request $request)
    {
        $request->validate([
            'email'    => 'required|string|email',
            'password' => 'required|string',
            'role'     => 'required|string|in:student,teacher,admin,super_admin', 
        ]);

        // Find the user profile relative to their unique email field string
        $user = User::where('email', $request->email)->first();

        // Uses manual hash check mapping cleanly against your custom column: 'password_hash'
        if ($user && Hash::check($request->password, $user->password_hash)) {
            
            // Check if user role matches the request selection
            if ($user->role !== $request->role) {
                return redirect()->back()
                    ->with('error', 'The selected role does not match your account type.')
                    ->withInput($request->only('email'));
            }

            // Prevent Super Admins from bypassing the secure 2FA workflow through this basic form
            if ($user->role === 'super_admin') {
                return redirect()->route('superadmin.login.page')
                    ->with('error', 'Super Admin authentication requires a secure validation token. Please log in here.')
                    ->withInput($request->only('email'));
            }

            // 🔒 ACCOUNT STATUS GATE: correct credentials alone aren't
            // enough to sign in. A self-registered teacher sitting in
            // 'pending' hasn't been approved by an Admin yet, and any
            // account an Admin has 'suspended' must stay locked out. This
            // runs for every role, not just teacher, so a suspended
            // student/admin account is blocked here too.
            if ($user->status === 'pending') {
                return redirect()->back()
                    ->with('error', 'Your teacher account is awaiting approval from your institution\'s Admin. You\'ll be able to log in once it\'s approved.')
                    ->withInput($request->only('email'));
            }

            if ($user->status !== 'active') {
                return redirect()->back()
                    ->with('error', 'Your account is not currently active. Please contact your institution\'s Admin.')
                    ->withInput($request->only('email'));
            }

            // Log standard users into the browser web state guard directly
            Auth::guard('web')->login($user);
            
            // UPDATE TIMESTAMPS: Save the login checkpoint into the active profile
            $user->last_login_at = now();
            $user->save();
            
            $request->session()->regenerate();

            // Redirect user to their corresponding dynamic layout workspace names
            switch ($user->role) {
                case 'admin':
                    return redirect()->intended('/admin/dashboard');
                case 'teacher':
                    return redirect()->route('teacher.dashboard');   
                case 'student':
                default:
                    return redirect()->intended('/student/dashboard');
            }
        }

        return redirect()->back()
            ->with('error', 'The provided credentials do not match our records.')
            ->withInput($request->only('email'));
    }

    /**
     * Handle incoming browser request password reset link generation.
     */
    public function sendResetLink(Request $request)
    {
        // 1. Validate that the input field matches an active user profile
        $request->validate([
            'email' => 'required|email|exists:users,email'
        ], [
            'email.exists' => 'We cannot find a user with that institutional email address.'
        ]);

        $user = User::where('email', $request->email)->first();

        // SUPER ADMIN CUSTOM RECOVERY FLOW (6-Digit OTP)
        if ($user && $user->role === 'super_admin') {

            if (!$this->sendSuperAdminOtp($user->email)) {
                return back()->withErrors([
                    'email' => 'We could not send your verification code right now. Please try again in a moment, or contact support if this keeps happening.',
                ])->withInput();
            }

            // Save the email in the session so the OTP page knows who is trying to recover their account
            session()->put('superadmin_attempt_email', $user->email);

            // Redirect them to the OTP input confirmation layout view page
            return redirect()->route('superadmin.verify.page');
        }

        // NORMAL USERS FLOW (Standard Reset Link)
        $status = Password::broker()->sendResetLink($request->only('email'));

        if ($status === Password::RESET_LINK_SENT) {
            session()->flash('reset_email', $request->email);
            return redirect()->route('password.success');
        }

        return back()->withErrors(['email' => __($status)]);
    }

    /**
     * Handle updating the database table with the newly changed password credentials.
     */
    public function resetPassword(Request $request)
    {
        $request->validate([
            'token'    => 'required',
            'email'    => 'required|email|exists:users,email',
            'password' => 'required|min:8|confirmed',
        ]);

        $status = Password::broker()->reset(
            $request->only('email', 'password', 'password_confirmation', 'token'),
            function ($user, $password) {
                // Intercepts update logic to sync password straight with your custom column name
                $user->password_hash = Hash::make($password);
                $user->save();
            }
        );

        if ($status === Password::PASSWORD_RESET) {
            return redirect()->route('login.page')->with('success', __($status));
        }

        return back()->withErrors(['email' => __($status)]);
    }

    /**
     * Destroy an authenticated web browser session.
     */
    public function logout(Request $request)
    {
        Auth::guard('web')->logout();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->route('login.page')->with('success', 'Logged out securely.');
    }

    /* |--------------------------------------------------------------------------
    | SUPER ADMIN PASSWORDLESS OTP LOGIC
    |--------------------------------------------------------------------------
    |
    */

    /**
     * Handle initiating the Super Admin passwordless login process by emailing a 6-digit OTP code.
     */
    public function sendSuperAdminCode(Request $request)
    {
        // Only validate the email input field and verify it exists in the database
        $request->validate([
            'email' => 'required|email|exists:users,email',
        ]);

        // Find user profile checking both email matching limits and super_admin privileges
        $user = User::where('email', $request->email)->where('role', 'super_admin')->first();

        // Secure boundary fallback check if user is not a super_admin
        if (!$user) {
            return back()->withErrors(['email' => 'Unauthorized administrative credentials.'])->withInput();
        }

        if (!$this->sendSuperAdminOtp($user->email)) {
            return back()->withErrors([
                'email' => 'We could not send your verification code right now. Please try again in a moment, or contact support if this keeps happening.',
            ])->withInput();
        }

        session()->put('superadmin_attempt_email', $request->email);

        return redirect()->route('superadmin.verify.page');
    }

    /**
     * Generate a fresh 6-digit OTP, cache it for 5 minutes, and email it to
     * the given address. This is the ONLY place that sends the Super Admin
     * login code — both password-reset and passwordless-login call this,
     * so a fix here (or a switch to a different mail provider) applies
     * everywhere at once instead of needing to be duplicated.
     *
     * Returns true if the email was handed off to the mail transport
     * successfully, false if it failed (bad SMTP credentials, connection
     * blocked, etc.) — callers should show the user a friendly error
     * instead of letting a 500 page leak transport details.
     */
    private function sendSuperAdminOtp(string $email): bool
    {
        $otp = str_pad(random_int(0, 999999), 6, '0', STR_PAD_LEFT);
        Cache::put('superadmin_otp_' . $email, $otp, now()->addMinutes(5));

        try {
            Mail::to($email)->send(new SuperAdminLoginCode($otp));
            return true;
        } catch (\Throwable $e) {
            // Log the real reason (SMTP auth failure, API timeout, etc.) for
            // you to diagnose — the user never sees this detail, only the
            // generic message from the caller.
            Log::error('Failed to send Super Admin OTP email', [
                'email' => $email,
                'error' => $e->getMessage(),
            ]);
            return false;
        }
    }

    /**
     * Verify the OTP token and authenticate the Super Admin.
     * FIXED: Normalized form parameter query match to fetch 'code' rather than 'verification_code'.
     */
    public function verifySuperAdminCode(Request $request)
    {
        $request->validate(['code' => 'required|string|size:6']);

        $email = session()->get('superadmin_attempt_email');

        if (!$email) {
            return redirect()->route('login.page')->withErrors(['email' => 'Authentication session has expired. Please log in again.']);
        }

        $cachedOtp = Cache::get('superadmin_otp_' . $email);

        if ($cachedOtp && $cachedOtp === $request->code) {
            
            $user = User::where('email', $email)->first();
            Auth::guard('web')->login($user);
            
            // Log access timestamp marker
            $user->last_login_at = now();
            $user->save();
            
            $request->session()->regenerate();

            Cache::forget('superadmin_otp_' . $email);
            session()->forget('superadmin_attempt_email');

            return redirect()->intended('/super-admin/dashboard');
        }

        return back()->withErrors(['code' => 'The system token code provided is invalid or has expired.']);
    }
}